<a href="https://colab.research.google.com/github/rohit8077/Python-Development/blob/main/Create_a_%22Matrix_Operations_Tool%22_using_Python_and_the_NumPy_library_The_application_should_allow_users_to_input_matrices_and_perform_operations_like_addition%2C_subtraction%2C_multiplication%2C_transpose%2C_and_determinant_calculation_Include_an_interactive_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def get_matrix_input(name):
    rows = int(input(f"Enter the number of rows for {name}: "))
    cols = int(input(f"Enter the number of columns for {name}: "))
    print(f"Enter the elements of {name} row-wise:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input().split()))
        if len(row) != cols:
            print("Invalid row length. Please enter again.")
            return get_matrix_input(name)
        matrix.append(row)
    return np.array(matrix)

def display_matrix(matrix, name="Matrix"):
    print(f"\n{name}:")
    print(matrix)

def matrix_operations():
    print("Matrix Operations Tool")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose")
    print("5. Determinant")
    choice = int(input("Select an operation (1-5): "))

    if choice in [1, 2, 3]:
        matrix1 = get_matrix_input("Matrix 1")
        matrix2 = get_matrix_input("Matrix 2")
        display_matrix(matrix1, "Matrix 1")
        display_matrix(matrix2, "Matrix 2")

        if choice == 1:  # Addition
            if matrix1.shape == matrix2.shape:
                result = matrix1 + matrix2
                display_matrix(result, "Result (Addition)")
            else:
                print("Addition not possible. Matrices must have the same dimensions.")
        elif choice == 2:  # Subtraction
            if matrix1.shape == matrix2.shape:
                result = matrix1 - matrix2
                display_matrix(result, "Result (Subtraction)")
            else:
                print("Subtraction not possible. Matrices must have the same dimensions.")
        elif choice == 3:  # Multiplication
            if matrix1.shape[1] == matrix2.shape[0]:
                result = np.dot(matrix1, matrix2)
                display_matrix(result, "Result (Multiplication)")
            else:
                print("Multiplication not possible. Columns of Matrix 1 must equal rows of Matrix 2.")

    elif choice == 4:  # Transpose
        matrix = get_matrix_input("Matrix")
        display_matrix(matrix, "Original Matrix")
        result = np.transpose(matrix)
        display_matrix(result, "Transpose")

    elif choice == 5:  # Determinant
        matrix = get_matrix_input("Square Matrix")
        if matrix.shape[0] == matrix.shape[1]:
            det = np.linalg.det(matrix)
            print(f"\nDeterminant: {det}")
        else:
            print("Determinant can only be calculated for square matrices.")
    else:
        print("Invalid choice. Please select a valid operation.")

if __name__ == "__main__":
    while True:
        matrix_operations()
        cont = input("Do you want to perform another operation? (yes/no): ").strip().lower()
        if cont != "yes":
            break


Matrix Operations Tool
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
Select an operation (1-5): 1
Enter the number of rows for Matrix 1: 2
Enter the number of columns for Matrix 1: 1
Enter the elements of Matrix 1 row-wise:
1
2
Enter the number of rows for Matrix 2: 2
Enter the number of columns for Matrix 2: 1
Enter the elements of Matrix 2 row-wise:
1
2

Matrix 1:
[[1.]
 [2.]]

Matrix 2:
[[1.]
 [2.]]

Result (Addition):
[[2.]
 [4.]]
